// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjyRDfA9zuoWGq9KL22f_rbtt5tZXMPsc',
    appId: '1:1039446342436:web:2a7f05fb8c740a6ad0d1b1',
    messagingSenderId: '1039446342436',
    projectId: 'empleados-a8258',
    authDomain: 'empleados-a8258.firebaseapp.com',
    databaseURL: 'https://empleados-a8258-default-rtdb.firebaseio.com',
    storageBucket: 'empleados-a8258.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtQLF7YnEL1T1pj9yaGYbAggbtKBaz8WI',
    appId: '1:1039446342436:android:c42dc47189a4943cd0d1b1',
    messagingSenderId: '1039446342436',
    projectId: 'empleados-a8258',
    databaseURL: 'https://empleados-a8258-default-rtdb.firebaseio.com',
    storageBucket: 'empleados-a8258.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiRx3VpKGIsTtMR89W-DqXHfDtjkzlpO4',
    appId: '1:1039446342436:ios:a3ec63ac57391ad2d0d1b1',
    messagingSenderId: '1039446342436',
    projectId: 'empleados-a8258',
    databaseURL: 'https://empleados-a8258-default-rtdb.firebaseio.com',
    storageBucket: 'empleados-a8258.firebasestorage.app',
    iosBundleId: 'com.example.fynix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiRx3VpKGIsTtMR89W-DqXHfDtjkzlpO4',
    appId: '1:1039446342436:ios:a3ec63ac57391ad2d0d1b1',
    messagingSenderId: '1039446342436',
    projectId: 'empleados-a8258',
    databaseURL: 'https://empleados-a8258-default-rtdb.firebaseio.com',
    storageBucket: 'empleados-a8258.firebasestorage.app',
    iosBundleId: 'com.example.fynix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjyRDfA9zuoWGq9KL22f_rbtt5tZXMPsc',
    appId: '1:1039446342436:web:e8f149dd2ed59945d0d1b1',
    messagingSenderId: '1039446342436',
    projectId: 'empleados-a8258',
    authDomain: 'empleados-a8258.firebaseapp.com',
    databaseURL: 'https://empleados-a8258-default-rtdb.firebaseio.com',
    storageBucket: 'empleados-a8258.firebasestorage.app',
  );
}
